[WIP] docs: Add Banks section
thenewboston-developers/thenewboston-js pull request #41
Opened 2020-12-11 04:56 UTC by AbhayAysola

closes #24 

Account Number: 8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1

2020-12-11 13:18 UTC, AbhayAysola commented
I accidentally made the commit massage `{` but it was supposed to be `docs: Getting Banks in Banks section`
Hope you don't mind 😅

2020-12-11 13:44 UTC, sno2 requested changes
Thanks for the update, please review my suggestions.

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +> The defaultPagination object is used as default options, when we make api calls later.
Please use "API" instead of "api".

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +However, if we do pass in our own options object, we can customize the `offset` and `limit` for each api call.
Please change "api" to "API".

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +```js
Please use the `ts` codeblock for all of these code examples.

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +bank.getAccounts();
Please await this as `getAccounts` is asynchronous.

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +bank.getAccounts({ limit: 10, offset: 30 });
Please await this has `getAccounts` is asynchronous.

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +As expected, we can also pass in the options object in the api call itself.
Please use "API" instead of "api".

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +> The behaviour of the options object is similar with all api calls.
"behaviour" -> "behavior"

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +bank.updateAccount("0cdd4ba04456ca169baca3d66eace869520c62fe84421329086e03d91a68acdb", 32, account); // 32 is the amount of trust
Please await this as `updateAccount` is asynchronous.

2020-12-11 13:44 UTC, sno2 commented on docs.md
> +Pretty similar to [Getting Accounts](#getting-accounts).
It might be better to say "Getting a list of transactions is fairly similar to [...]".

2020-12-11 14:20 UTC, AbhayAysola commented
I made all the requested changes. Just wanted to know if everything else is also alright.

2020-12-11 14:22 UTC, sno2 commented
> I made all the requested changes. Just wanted to know if everything else is also alright.

Yeah, looking good👍

2020-12-11 15:00 UTC, sno2 requested changes
Looking good, expect for the missing period😉

2020-12-11 15:24 UTC, AbhayAysola commented on docs.md
> +Getting a list of blocks is quite similar to all the previous API calls. For this, we use `Bank.getBlocks`
My bad.

2020-12-12 05:48 UTC, sno2 approved these changes
Thanks, we are probably going to adjust some things (to normalize the doc style) further along the line, but this is awesome for a starter with some code examples & explanations👍

2020-12-12 05:50 UTC, merged